version: '3'
services:
  db:
    container_name: dart-mysql-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Tokyo
    command: mysqld --default-authentication-plugin=mysql_native_password